#port config
server:
  port: 8082

eureka:
  client:
    serviceUrl:
      #setting registry adress
      defaultZone: http://localhost:8081/eureka/

spring:
  application:
    #current install name
    name: eureka-client-A

