# port config
server:
        port: 8081

eureka:
  instance:
    #setting current instace host name
    hostname: localhost
  client:
    #Since the app is a registry, it is set to false, which means you are not registering
    #yourself with the registry.
    register-with-eureka: false
    #Since the role of the registry is to maintain a service instance, it does not need to
    #retrieve the service, so it is also set to false.
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    #app name config
    name: eureka-registry
